apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: airflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding-airflow-ingestion
  namespace: ingestion
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: airflow
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding-airflow-anonymized
  namespace: anonymized
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: airflow
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io