name: Publish Tagged Image

on:
  push:
    tags:
      - 2.1.4-python3*_*
      - 2.2.5-python3*_*

jobs:
  publish-notebook:
    name: Publish airflow image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get airflow version
        run: |
          AIRFLOW_VERSION=${GITHUB_REF_NAME%_*}
          echo "AIRFLOW_VERSION=$(echo $AIRFLOW_VERSION)" >> $GITHUB_ENV
      - name: Log into registry
        run: echo "${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.FERLAB_DOCKER_HUB_USER }} --password-stdin
      - name: Build airflow
        run: docker build -t ferlabcrsj/airflow:${GITHUB_REF_NAME} .
        working-directory: airflow${{ env.AIRFLOW_VERSION }}
      - name: Push airflow
        run: docker push ferlabcrsj/airflow:${GITHUB_REF_NAME}
        working-directory: airflow${{ env.AIRFLOW_VERSION }}
