name: Docker CD

on:
  push:
    branches:
      - master

jobs:
  publish-notebook:
    name: Docker CD
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.FERLAB_DOCKER_HUB_USER }} --password-stdin

      - name: Build image airflow2.1.4-python3.8
        run: docker build -t ferlabcrsj/airflow:2.1.4-python3.8 .
        working-directory: airflow2.1.4-python3.8
      - name: Push image airflow2.1.4-python3.8
        run: docker push ferlabcrsj/airflow:2.1.4-python3.8
        working-directory: airflow2.1.4-python3.8

      - name: Build image airflow:2.2.5-python3.8
        run: docker build -t ferlabcrsj/airflow:2.2.5-python3.8 .
        working-directory: airflow2.2.5-python3.8
      - name: Push image airflow:2.2.5-python3.8
        run: docker push ferlabcrsj/airflow:2.2.5-python3.8
        working-directory: airflow2.2.5-python3.8
